# This is a basic workflow to help you get started with Actions

name: Build Sphinx-Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ develop, master ]
    types: [ opened, reopened, synchronize, ready_for_review ]
  push:
    branches: [ develop, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2

    # Setup pandoc
    - name: Setup Pandoc
      run: |
        choco install pandoc

    # Setup pipenv
    - name: Setup pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv sync --dev --clear --verbose

    # Check Sphinx
    - name: Check Sphinx
      run: |
        pipenv run --verbose make linkcheck
        pipenv run --verbose make doctest
        pipenv run --verbose make coverage

    # Build Sphinx docs
    - name: Build Sphinx docs
      run: pipenv run --verbose make html



  # Deploy Before
  deploy-before:
    if: success() && contains(github.event.name, 'push') && contains(github.ref, 'refs/heads/develop')
    needs: build
    runs-on: windows-latest

    steps:

    # Copy html pages
    - name: Copy html pages
      run: |
        Remove-Item -Path ".\docs\*" -Recurse
        Copy-Item -Path ".\build\html\*" -Destination ".\docs" -Recurse

    # Commit files
    - name: Commit files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git commit --verbose --message "${GITHUB_WORKFLOW}: ${GITHUB_RUN_NUMBER}" -- .\docs

    # Push
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Pull Request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.8.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: 'Update master branch'
        assignees: murnana
        reviewers: murnana
        draft: false
        branch: master
