# This is a basic workflow to help you get started with Actions

name: Check PullRequest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened, synchronize, ready_for_review ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2

    # Setup pandoc
    - name: Setup Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.10/pandoc-2.10-1-amd64.deb
        sudo dpkg -i pandoc-2.10-1-amd64.deb

    # Setup pipenv
    - name: Setup pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv sync --dev --clear --verbose

    # Check Sphinx
    - name: Check Sphinx
      run: |
        pipenv run --verbose make linkcheck
        pipenv run --verbose make doctest
        pipenv run --verbose make coverage

    # Build Sphinx docs
    - name: Build Sphinx docs
      run: pipenv run --verbose make html
